import 'vant/es/style/base.less'
import 'vant/es/dialog/index.less'
import 'vant/es/popup/index.less'
import 'vant/es/overlay/index.less'
import 'vant/es/info/index.less'
import 'vant/es/icon/index.less'
import 'vant/es/loading/index.less'
import 'vant/es/button/index.less'
